# Generated by Django 4.2.1 on 2024-02-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Национальное блюдо', 'verbose_name_plural': 'Выбор национальных блюд'},
        ),
    ]
